import type { OpportunityRow } from "@/types/database";

const now = new Date().toISOString();

type OpportunitySeed = Omit<
  OpportunityRow,
  | "created_at"
  | "updated_at"
  | "procurement_score"
  | "procurement_signal_count"
  | "procurement_evidence"
  | "procurement_buyer_types"
  | "procurement_workflow_tags"
> &
  Partial<
    Pick<
      OpportunityRow,
      | "procurement_score"
      | "procurement_signal_count"
      | "procurement_evidence"
      | "procurement_buyer_types"
      | "procurement_workflow_tags"
    >
  >;

function opp(seed: OpportunitySeed): OpportunityRow {
  return {
    ...seed,
    primary_buyer: seed.primary_buyer ?? seed.target_buyer,
    procurement_score: seed.procurement_score ?? null,
    procurement_signal_count: seed.procurement_signal_count ?? null,
    procurement_evidence: seed.procurement_evidence ?? null,
    procurement_buyer_types: seed.procurement_buyer_types ?? null,
    procurement_workflow_tags: seed.procurement_workflow_tags ?? null,
    created_at: now,
    updated_at: now,
  };
}

export const mockOpportunities: OpportunityRow[] = [
  opp({
    id: "1",
    title: "Contractor OSHA Documentation Tracker",
    short_summary:
      "Audit-ready safety logs for small contractors who still track OSHA compliance manually.",
    overall_score: 78,
    best_first_asset: "Spreadsheet / Template",
    complexity: "Low",
    tags: ["B2B", "Compliance"],
    status: "published",
    problem_summary:
      "Small contractors struggle to maintain OSHA-compliant safety logs and documentation.",
    evidence_summary:
      "Compliance updates and safety coordinator job postings indicate ongoing documentation burden.",
    key_pain_drivers: ["Manual tracking", "Audit risk", "Inconsistent reporting"],
    pressure_score: 72,
    demand_score: 65,
    wedge_score: 58,
    freshness_score: 70,
    buildability_score: 88,
    asset_fit_score: 91,
    friction_score: 76,
    complaint_signal_strength: 68,
    asset_path_1: "Spreadsheet tracker",
    asset_path_2: "n8n workflow automation",
    asset_path_3: "Lightweight SaaS",
    asset_reason: "Structured workflow makes templates the fastest path to value.",
    expansion_ladder: "Template → Dashboard → Workflow automation → SaaS",
    target_buyer: "Small contractors (5–50 employees)",
    primary_buyer: "Safety coordinator at SMB contractors",
    secondary_buyers: ["Operations manager", "Owner-operator"],
    buyer_tags: ["smb", "contractor", "local"],
    industry_tags: ["construction", "compliance"],
    asset_strategy: "Productized compliance template with upsell automation",
    core_workflow: "Safety logging and compliance reporting",
    initial_wedge: "Simple audit-ready log system",
    time_to_value: "Fast",
    underserved_segment: "Small contractors underserved by enterprise EHS tools",
    competitor_summary: "Most tools are enterprise-focused, complex, and expensive",
    avoid: "Do not compete on full feature parity with enterprise tools",
    differentiation: "Focus on simplicity, speed, and audit-ready outputs",
    entry_strategy: "Start with downloadable template, expand into automation",
    strategic_importance: "Compliance burden is increasing while tooling remains complex",
  }),
  opp({
    id: "2",
    title: "Vendor Risk Portal for Healthcare Ops",
    short_summary:
      "Lightweight vendor onboarding and risk scoring for hospital procurement teams.",
    overall_score: 74,
    best_first_asset: "Vendor Intake Form + Scorecard",
    complexity: "Low",
    tags: ["healthcare", "procurement", "risk"],
    status: "published",
    problem_summary: "Hospital ops teams lack a unified vendor risk intake process.",
    evidence_summary: "RFP language consistently references manual vendor questionnaires.",
    key_pain_drivers: ["Slow onboarding", "Inconsistent risk scoring"],
    pressure_score: 70,
    demand_score: 72,
    wedge_score: 68,
    freshness_score: 66,
    buildability_score: 85,
    asset_fit_score: 75,
    friction_score: 74,
    complaint_signal_strength: 62,
    asset_path_1: "Intake form",
    asset_path_2: "Risk scorecard",
    asset_path_3: "Renewal tracking",
    asset_reason: "Form-based wedge maps directly to existing procurement steps.",
    expansion_ladder: "Intake → Scorecard → Vendor lifecycle",
    target_buyer: "Director of Procurement",
    primary_buyer: "Director of Procurement",
    secondary_buyers: ["Vendor risk manager"],
    buyer_tags: ["enterprise", "mid_market", "procurement"],
    industry_tags: ["healthcare", "compliance"],
    asset_strategy: "Intake form wedge into procurement workflow",
    core_workflow: "Intake → Score → Approve → Renew",
    initial_wedge: "Standardized vendor questionnaire",
    time_to_value: "1 week",
    underserved_segment: "Regional hospital networks",
    competitor_summary: "Enterprise VRM platforms priced for health systems.",
    avoid: "Deep EHR integrations initially",
    differentiation: "Healthcare-specific questionnaire templates",
    entry_strategy: "Template library + export to existing tools",
    strategic_importance: "Vendor risk is a recurring compliance requirement with clear ROI.",
    procurement_score: 8,
    procurement_signal_count: 2,
    procurement_evidence:
      "2 SAM.gov signal(s), avg score 7.5 | Department of Health and Human Services: Vendor Risk Management Platform | VA: Third-Party Risk Tracking System",
    procurement_buyer_types: [
      "Department of Health and Human Services",
      "Department of Veterans Affairs",
    ],
    procurement_workflow_tags: ["compliance_reporting", "case_management"],
  }),
  opp({
    id: "3",
    title: "AI Policy Toolkit for HR Teams",
    short_summary:
      "Draft and distribute internal AI usage policies with acknowledgment tracking.",
    overall_score: 65,
    best_first_asset: "Policy Template Pack",
    complexity: "Low",
    tags: ["hr", "ai", "policy"],
    status: "published",
    problem_summary: "HR teams need fast, compliant AI usage policies as adoption accelerates.",
    evidence_summary: "Rising volume of HR policy update requests tied to AI tool rollouts.",
    key_pain_drivers: ["Policy lag", "Inconsistent employee guidance"],
    pressure_score: 60,
    demand_score: 68,
    wedge_score: 62,
    freshness_score: 80,
    buildability_score: 90,
    asset_fit_score: 70,
    friction_score: 55,
    complaint_signal_strength: 48,
    asset_path_1: "Template pack",
    asset_path_2: "Acknowledgment tracker",
    asset_path_3: "Policy version control",
    asset_reason: "Templates are immediately usable without IT involvement.",
    expansion_ladder: "Templates → Tracking → Governance hub",
    target_buyer: "HR Operations Lead",
    primary_buyer: "HR Operations Lead",
    secondary_buyers: ["People ops manager"],
    buyer_tags: ["mid_market", "hr"],
    industry_tags: ["hr", "compliance"],
    asset_strategy: "Template-led advisory offer with tracking upsell",
    core_workflow: "Draft → Review → Publish → Track",
    initial_wedge: "Pre-built AI policy templates",
    time_to_value: "3 days",
    underserved_segment: "Mid-size companies (200–2000 employees)",
    competitor_summary: "Legal consultancies sell one-off policy docs.",
    avoid: "Positioning as legal advice",
    differentiation: "HR-ready templates with acknowledgment workflow",
    entry_strategy: "Free template download → paid tracking",
    strategic_importance: "Every company adopting AI needs policy infrastructure.",
  }),
  opp({
    id: "4",
    title: "Crypto Custody Compliance Monitor",
    short_summary:
      "Track qualified custodian rule changes and map obligations for asset managers.",
    overall_score: 81,
    best_first_asset: "Regulatory Change Dashboard",
    complexity: "Medium",
    tags: ["fintech", "compliance", "crypto"],
    status: "published",
    problem_summary:
      "Crypto asset managers lack a structured view of evolving custody compliance obligations.",
    evidence_summary:
      "SEC rulemaking and enforcement actions create recurring compliance review cycles.",
    key_pain_drivers: ["Regulatory uncertainty", "Manual monitoring", "Audit exposure"],
    pressure_score: 85,
    demand_score: 74,
    wedge_score: 77,
    freshness_score: 88,
    buildability_score: 72,
    asset_fit_score: 69,
    friction_score: 58,
    complaint_signal_strength: 71,
    asset_path_1: "Alert digest",
    asset_path_2: "Obligation tracker",
    asset_path_3: "Audit evidence pack",
    asset_reason: "Compliance teams already maintain spreadsheets — structured tracker is a natural wedge.",
    expansion_ladder: "Alerts → Tracker → Evidence automation",
    target_buyer: "Chief Compliance Officer",
    primary_buyer: "Chief Compliance Officer",
    secondary_buyers: ["Fund COO", "Risk officer"],
    buyer_tags: ["enterprise", "financial_services"],
    industry_tags: ["financial_services", "compliance"],
    asset_strategy: "Monitoring dashboard with thesis-ready exports",
    core_workflow: "Monitor → Map → Evidence → Report",
    initial_wedge: "Weekly regulatory change digest",
    time_to_value: "2 weeks",
    underserved_segment: "Mid-size crypto asset managers",
    competitor_summary: "Enterprise GRC suites are heavy and slow to configure.",
    avoid: "Competing as a trading or custody platform",
    differentiation: "Crypto-custody-specific obligation mapping",
    entry_strategy: "Paid digest → obligation workspace",
    strategic_importance: "Custody rules are a durable compliance pressure vector.",
  }),
  opp({
    id: "5",
    title: "Municipal Permit Status Tracker",
    short_summary:
      "Give local contractors a single view of permit status across city portals.",
    overall_score: 69,
    best_first_asset: "Permit Status Board",
    complexity: "Medium",
    tags: ["government", "construction", "workflow"],
    status: "published",
    problem_summary:
      "Contractors waste hours checking fragmented municipal permit portals.",
    evidence_summary:
      "Forum complaints and permit backlog reporting show repeated workflow friction.",
    key_pain_drivers: ["Portal fragmentation", "Status ambiguity", "Project delays"],
    pressure_score: 63,
    demand_score: 61,
    wedge_score: 64,
    freshness_score: 75,
    buildability_score: 78,
    asset_fit_score: 82,
    friction_score: 84,
    complaint_signal_strength: 79,
    asset_path_1: "Status board",
    asset_path_2: "Notification workflow",
    asset_path_3: "Multi-city rollup",
    asset_reason: "Status aggregation is a narrow, high-friction workflow with clear ROI.",
    expansion_ladder: "Single city → Notifications → Multi-city",
    target_buyer: "Local general contractor office manager",
    primary_buyer: "Local general contractor office manager",
    secondary_buyers: ["Project coordinator"],
    buyer_tags: ["smb", "local", "public_sector"],
    industry_tags: ["construction", "public_sector", "logistics"],
    asset_strategy: "Workflow board sold as implementation package",
    core_workflow: "Submit → Track → Escalate → Close",
    initial_wedge: "Single-city permit board",
    time_to_value: "1 week",
    underserved_segment: "SMB contractors working across 2–5 municipalities",
    competitor_summary: "Generic project tools ignore permit-specific status semantics.",
    avoid: "Building a full construction ERP",
    differentiation: "Permit-native status semantics and alerts",
    entry_strategy: "City-specific pilot → regional expansion",
    strategic_importance: "Permit delays are a visible, recurring operational pain.",
  }),
  opp({
    id: "6",
    title: "Developer API Key Governance Kit",
    short_summary:
      "Help engineering teams inventory, rotate, and audit third-party API keys.",
    overall_score: 76,
    best_first_asset: "API Key Inventory Template",
    complexity: "Low",
    tags: ["developer tools", "security", "saas"],
    status: "published",
    problem_summary:
      "Engineering teams lack a lightweight system for API key lifecycle management.",
    evidence_summary:
      "Incident postmortems and security questionnaires repeatedly cite key sprawl.",
    key_pain_drivers: ["Key sprawl", "Rotation lag", "Audit gaps"],
    pressure_score: 68,
    demand_score: 77,
    wedge_score: 71,
    freshness_score: 73,
    buildability_score: 86,
    asset_fit_score: 88,
    friction_score: 69,
    complaint_signal_strength: 52,
    asset_path_1: "Inventory template",
    asset_path_2: "Rotation checklist automation",
    asset_path_3: "Governance dashboard",
    asset_reason: "Inventory template is immediately useful without platform integration.",
    expansion_ladder: "Template → Automation → Dashboard",
    target_buyer: "Engineering manager",
    primary_buyer: "Engineering manager",
    secondary_buyers: ["Platform lead", "Security champion"],
    buyer_tags: ["mid_market", "enterprise", "developer"],
    industry_tags: ["developer_tools", "compliance"],
    asset_strategy: "Template-to-SaaS governance ladder",
    core_workflow: "Inventory → Rotate → Audit → Report",
    initial_wedge: "Shared key inventory with owners",
    time_to_value: "3 days",
    underserved_segment: "Teams between spreadsheets and enterprise vaults",
    competitor_summary: "Enterprise secret managers are overkill for many teams.",
    avoid: "Positioning as a full secrets platform on day one",
    differentiation: "Developer-native inventory with rotation rituals",
    entry_strategy: "Template lead magnet → team workspace",
    strategic_importance: "API key incidents remain a top startup security failure mode.",
  }),
  opp({
    id: "7",
    title: "Regional Hospital Staffing Gap Forecaster",
    short_summary:
      "Forecast nurse staffing gaps using turnover signals and local hiring friction.",
    overall_score: 71,
    best_first_asset: "Staffing Risk Brief",
    complexity: "High",
    tags: ["healthcare", "workforce", "analytics"],
    status: "published",
    problem_summary:
      "Regional hospitals struggle to anticipate staffing gaps before patient care is affected.",
    evidence_summary:
      "Turnover filings, job posting velocity, and union updates align on rising risk.",
    key_pain_drivers: ["Turnover spikes", "Agency spend", "Coverage risk"],
    pressure_score: 74,
    demand_score: 66,
    wedge_score: 70,
    freshness_score: 82,
    buildability_score: 64,
    asset_fit_score: 67,
    friction_score: 61,
    complaint_signal_strength: 73,
    asset_path_1: "Risk brief",
    asset_path_2: "Forecast dashboard",
    asset_path_3: "Retention playbook",
    asset_reason: "Brief format fits hospital leadership review cycles.",
    expansion_ladder: "Brief → Dashboard → Playbooks",
    target_buyer: "Chief Nursing Officer",
    primary_buyer: "Chief Nursing Officer",
    secondary_buyers: ["HR director", "Operations VP"],
    buyer_tags: ["enterprise", "healthcare"],
    industry_tags: ["healthcare", "hr"],
    asset_strategy: "Advisory brief with forecast upsell",
    core_workflow: "Signal → Forecast → Brief → Action",
    initial_wedge: "Monthly staffing risk brief",
    time_to_value: "2 weeks",
    underserved_segment: "Regional hospital networks",
    competitor_summary: "Workforce analytics suites require long implementations.",
    avoid: "Competing with full workforce management suites",
    differentiation: "Healthcare-specific staffing risk framing",
    entry_strategy: "Brief subscription → forecast workspace",
    strategic_importance: "Staffing volatility is a board-level operational risk.",
  }),
  opp({
    id: "8",
    title: "Warehouse Pick-Path Friction Auditor",
    short_summary:
      "Identify pick-path inefficiencies from operational complaints and WMS export patterns.",
    overall_score: 67,
    best_first_asset: "Friction Audit Workbook",
    complexity: "Medium",
    tags: ["logistics", "operations", "workflow"],
    status: "published",
    problem_summary:
      "Warehouse operators know pick-path friction exists but lack a structured audit method.",
    evidence_summary:
      "Operator complaints, throughput variance, and WMS export anomalies cluster on pick paths.",
    key_pain_drivers: ["Pick errors", "Throughput variance", "Training drag"],
    pressure_score: 58,
    demand_score: 63,
    wedge_score: 66,
    freshness_score: 68,
    buildability_score: 80,
    asset_fit_score: 84,
    friction_score: 88,
    complaint_signal_strength: 77,
    asset_path_1: "Audit workbook",
    asset_path_2: "Heatmap analysis",
    asset_path_3: "Continuous monitoring",
    asset_reason: "Workbook audit can start without WMS integration.",
    expansion_ladder: "Workbook → Heatmap → Monitoring",
    target_buyer: "Warehouse operations manager",
    primary_buyer: "Warehouse operations manager",
    secondary_buyers: ["Continuous improvement lead"],
    buyer_tags: ["mid_market", "logistics"],
    industry_tags: ["logistics", "construction"],
    asset_strategy: "Consulting-led audit converted into monitoring product",
    core_workflow: "Observe → Audit → Recommend → Monitor",
    initial_wedge: "Pick-path friction workbook",
    time_to_value: "1 week",
    underserved_segment: "Mid-market 3PL and regional distributors",
    competitor_summary: "WMS vendors optimize configuration, not operational friction discovery.",
    avoid: "Leading with full WMS replacement",
    differentiation: "Complaint-grounded friction audit methodology",
    entry_strategy: "Paid audit → monitoring subscription",
    strategic_importance: "Pick-path friction directly impacts margin and SLA performance.",
  }),
  opp({
    id: "9",
    title: "Internal Venture Bet Comparison Workspace",
    short_summary:
      "Compare validation signals across a studio portfolio before allocating operator time.",
    overall_score: 73,
    best_first_asset: "Bet Comparison Canvas",
    complexity: "Medium",
    tags: ["venture", "portfolio", "validation"],
    status: "draft",
    problem_summary:
      "Venture studios lack a lightweight way to compare validation strength across bets.",
    evidence_summary:
      "Studio operators repeatedly rebuild comparison spreadsheets for IC reviews.",
    key_pain_drivers: ["Subjective prioritization", "Signal sprawl", "Slow IC prep"],
    pressure_score: 62,
    demand_score: 58,
    wedge_score: 75,
    freshness_score: 71,
    buildability_score: 83,
    asset_fit_score: 79,
    friction_score: 52,
    complaint_signal_strength: 44,
    asset_path_1: "Comparison canvas",
    asset_path_2: "Signal rollup",
    asset_path_3: "IC review workspace",
    asset_reason: "Canvas format mirrors existing studio rituals.",
    expansion_ladder: "Canvas → Rollup → IC workspace",
    target_buyer: "Venture studio managing partner",
    primary_buyer: "Venture studio managing partner",
    secondary_buyers: ["Head of ventures"],
    buyer_tags: ["venture_studio", "enterprise"],
    industry_tags: ["developer_tools", "financial_services"],
    asset_strategy: "Portfolio comparison workspace for repeated bets",
    core_workflow: "Collect → Compare → Prioritize → Staff",
    initial_wedge: "Shared bet comparison canvas",
    time_to_value: "1 week",
    underserved_segment: "Studios with 5–20 active concepts",
    competitor_summary: "Investor CRMs do not model venture validation signals well.",
    avoid: "Positioning as a fund admin tool",
    differentiation: "Validation-signal-native comparison for studios",
    entry_strategy: "Studio pilot → portfolio license",
    strategic_importance: "Studios need repeatable bet comparison, not one-off memos.",
  }),
];
