import type {
  KeywordMetricRow,
  KeywordSetRow,
  MarketProofRecordRow,
  OpportunityRow,
  ProblemZoneRow,
  ProblemZoneSignalRow,
  RawSignalRow,
  SignalRow,
  SourceRow,
  WorkflowFrictionSignalRow,
  ZoneRow,
} from "@/types/database";

const now = new Date().toISOString();

export const mockOpportunities: OpportunityRow[] = [
  {
    id: "1",
    title: "Contractor OSHA Documentation Tracker",
    short_summary:
      "Audit-ready safety logs for small contractors who still track OSHA compliance manually.",
    overall_score: 78,
    best_first_asset: "Spreadsheet / Template",
    complexity: "Low",
    tags: ["B2B", "Compliance"],
    status: "published",
    problem_summary:
      "Small contractors struggle to maintain OSHA-compliant safety logs and documentation, often relying on manual processes that break during audits.",
    evidence_summary:
      "Recent compliance updates and recurring job postings for safety coordinators indicate ongoing documentation burden. Search demand shows consistent queries around OSHA logs and safety tracking.",
    key_pain_drivers: [
      "Manual tracking",
      "Audit risk",
      "Inconsistent reporting",
      "Lack of simple tools",
    ],
    pressure_score: 7,
    demand_score: 6,
    wedge_score: 5,
    buildability_score: 8,
    asset_fit_score: 9,
    asset_path_1: "Spreadsheet tracker",
    asset_path_2: "n8n workflow automation",
    asset_path_3: "Lightweight SaaS",
    asset_reason:
      "The workflow is structured and repeatable, making a template the fastest way to deliver value.",
    expansion_ladder: "Template → Dashboard → Workflow automation → SaaS",
    target_buyer: "Small contractors (5–50 employees)",
    core_workflow: "Safety logging and compliance reporting",
    initial_wedge: "Simple audit-ready log system",
    time_to_value: "Fast",
    underserved_segment:
      "Small contractors underserved by enterprise EHS tools",
    competitor_summary:
      "Most tools are enterprise-focused, complex, and expensive",
    avoid: "Do not compete on full feature parity with enterprise tools",
    differentiation:
      "Focus on simplicity, speed, and audit-ready outputs",
    entry_strategy:
      "Start with downloadable template, expand into automation",
    strategic_importance:
      "Compliance burden is increasing while tooling remains complex",
    created_at: now,
    updated_at: now,
  },
  {
    id: "2",
    title: "Vendor Risk Portal for Healthcare Ops",
    short_summary:
      "Lightweight vendor onboarding and risk scoring for hospital procurement teams.",
    overall_score: 74,
    best_first_asset: "Vendor Intake Form + Scorecard",
    complexity: "Low",
    tags: ["healthcare", "procurement", "risk"],
    status: "published",
    problem_summary:
      "Hospital ops teams lack a unified vendor risk intake process.",
    evidence_summary:
      "RFP language consistently references manual vendor questionnaires.",
    key_pain_drivers: ["Slow onboarding", "Inconsistent risk scoring"],
    pressure_score: 70,
    demand_score: 72,
    wedge_score: 68,
    buildability_score: 85,
    asset_fit_score: 75,
    asset_path_1: "Intake form",
    asset_path_2: "Risk scorecard",
    asset_path_3: "Renewal tracking",
    asset_reason: "Form-based wedge maps directly to existing procurement steps.",
    expansion_ladder: "Intake → Scorecard → Vendor lifecycle",
    target_buyer: "Director of Procurement",
    core_workflow: "Intake → Score → Approve → Renew",
    initial_wedge: "Standardized vendor questionnaire",
    time_to_value: "1 week",
    underserved_segment: "Regional hospital networks",
    competitor_summary: "Enterprise VRM platforms priced for health systems.",
    avoid: "Deep EHR integrations initially",
    differentiation: "Healthcare-specific questionnaire templates",
    entry_strategy: "Template library + export to existing tools",
    strategic_importance:
      "Vendor risk is a recurring compliance requirement with clear ROI.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "3",
    title: "AI Policy Toolkit for HR Teams",
    short_summary:
      "Draft and distribute internal AI usage policies with acknowledgment tracking.",
    overall_score: 65,
    best_first_asset: "Policy Template Pack",
    complexity: "Low",
    tags: ["hr", "ai", "policy"],
    status: "draft",
    problem_summary:
      "HR teams need fast, compliant AI usage policies as adoption accelerates.",
    evidence_summary:
      "Rising volume of HR policy update requests tied to AI tool rollouts.",
    key_pain_drivers: ["Policy lag", "Inconsistent employee guidance"],
    pressure_score: 60,
    demand_score: 68,
    wedge_score: 62,
    buildability_score: 90,
    asset_fit_score: 70,
    asset_path_1: "Template pack",
    asset_path_2: "Acknowledgment tracker",
    asset_path_3: "Policy version control",
    asset_reason: "Templates are immediately usable without IT involvement.",
    expansion_ladder: "Templates → Tracking → Governance hub",
    target_buyer: "HR Operations Lead",
    core_workflow: "Draft → Review → Publish → Track",
    initial_wedge: "Pre-built AI policy templates",
    time_to_value: "3 days",
    underserved_segment: "Mid-size companies (200–2000 employees)",
    competitor_summary: "Legal consultancies sell one-off policy docs.",
    avoid: "Positioning as legal advice",
    differentiation: "HR-ready templates with acknowledgment workflow",
    entry_strategy: "Free template download → paid tracking",
    strategic_importance:
      "Every company adopting AI needs policy infrastructure.",
    created_at: now,
    updated_at: now,
  },
];

export const mockSignals: SignalRow[] = [
  {
    id: "s1",
    title: "SEC proposes new crypto custody rules",
    source: "Federal Register",
    type: "regulatory",
    processed: true,
    created_at: now,
  },
  {
    id: "s2",
    title: "Hospital vendor breach highlights third-party risk",
    source: "Healthcare IT News",
    type: "news",
    processed: false,
    created_at: now,
  },
];

export const mockRawSignals: RawSignalRow[] = [
  {
    id: "rs1",
    source_id: "src3",
    title: "SEC proposes new crypto custody rules",
    summary:
      "SEC rulemaking notice for qualified custodian requirements affecting crypto asset managers.",
    raw_text: null,
    source_url: "https://www.federalregister.gov/documents/2026/01/15/2026-01234",
    published_at: now,
    observed_at: now,
    workflow_lane: "pressure_discovery",
    source_type: "trigger",
    cadence_class: "daily",
    freshness_label: "fresh",
    geography: "US",
    state: null,
    metro: null,
    industry_tags: ["financial services", "crypto"],
    buyer_tags: [],
    regulation_tags: ["SEC", "custody"],
    keyword_tags: [],
    dedup_hash: "seed-federal-register-sec-crypto-custody",
    clustered: false,
    raw_importance_score: 4,
    needs_review: false,
    created_at: now,
  },
  {
    id: "rs2",
    source_id: "src2",
    title: "Hospital vendor breach highlights third-party environmental compliance risk",
    summary:
      "EPA enforcement context for healthcare facilities with outsourced waste handling vendors.",
    raw_text: null,
    source_url: "https://echo.epa.gov/facilities/example",
    published_at: now,
    observed_at: now,
    workflow_lane: "pressure_discovery",
    source_type: "trigger",
    cadence_class: "weekly",
    freshness_label: "recent",
    geography: "US",
    state: null,
    metro: null,
    industry_tags: ["healthcare", "environmental"],
    buyer_tags: [],
    regulation_tags: ["EPA", "RCRA"],
    keyword_tags: [],
    dedup_hash: "seed-epa-echo-hospital-vendor-breach",
    clustered: false,
    raw_importance_score: 3,
    needs_review: true,
    created_at: now,
  },
  {
    id: "rs3",
    source_id: "src5",
    title: "Teams request native compliance workflow templates in issue trackers",
    summary:
      "Repeated friction signals from open-source repos asking for built-in audit trail exports.",
    raw_text: null,
    source_url: "https://github.com/example/repo/issues/4821",
    published_at: now,
    observed_at: now,
    workflow_lane: "workflow_friction",
    source_type: "friction",
    cadence_class: "daily",
    freshness_label: "recent",
    geography: "Global",
    state: null,
    metro: null,
    industry_tags: ["developer tools", "compliance"],
    buyer_tags: [],
    regulation_tags: [],
    keyword_tags: [],
    dedup_hash: "seed-github-issues-compliance-workflow-templates",
    clustered: false,
    raw_importance_score: 2,
    needs_review: true,
    created_at: now,
  },
];

export const mockSources: SourceRow[] = [
  {
    id: "src1",
    name: "OSHA",
    workflow_lane: "pressure_discovery",
    source_type: "structural",
    category: "Occupational Safety",
    api_status: "semi_manual",
    cadence: "monthly",
    geography_scope: "US",
    reliability_score: 5,
    freshness_window_days: 30,
    active: true,
    last_sync_at: now,
    notes:
      "OSHA enforcement data and compliance guidance for workplace safety pressure signals.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "src2",
    name: "EPA ECHO",
    workflow_lane: "pressure_discovery",
    source_type: "trigger",
    category: "Environmental Compliance",
    api_status: "automated",
    cadence: "weekly",
    geography_scope: "US",
    reliability_score: 5,
    freshness_window_days: 14,
    active: true,
    last_sync_at: now,
    notes:
      "EPA Enforcement and Compliance History Online for facility violations and triggers.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "src3",
    name: "Federal Register",
    workflow_lane: "pressure_discovery",
    source_type: "trigger",
    category: "Regulatory",
    api_status: "automated",
    cadence: "daily",
    geography_scope: "US",
    reliability_score: 5,
    freshness_window_days: 7,
    active: true,
    last_sync_at: now,
    notes:
      "Primary regulatory trigger source for new rules, notices, and compliance deadlines.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "src4",
    name: "DataForSEO",
    workflow_lane: "demand_validation",
    source_type: "structural",
    category: "Search Demand",
    api_status: "automated",
    cadence: "weekly",
    geography_scope: "US",
    reliability_score: 4,
    freshness_window_days: 30,
    active: true,
    last_sync_at: now,
    notes:
      "Keyword volume, CPC, competition, and trend enrichment for demand validation.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "src5",
    name: "GitHub Issues",
    workflow_lane: "workflow_friction",
    source_type: "friction",
    category: "Developer Forums",
    api_status: "automated",
    cadence: "daily",
    geography_scope: "Global",
    reliability_score: 3,
    freshness_window_days: 14,
    active: true,
    last_sync_at: now,
    notes:
      "Workflow friction signals from open-source repos, feature requests, and workarounds.",
    created_at: now,
    updated_at: now,
  },
];

export const mockZones: ZoneRow[] = [
  {
    id: "z1",
    title: "Fintech Compliance",
    summary: "Regulatory monitoring and workflow tools for fintech compliance teams.",
    industry: "Financial Services",
    buyer: "Head of Compliance",
    created_at: now,
  },
  {
    id: "z2",
    title: "Healthcare Procurement",
    summary: "Vendor risk and procurement tooling for hospital networks.",
    industry: "Healthcare",
    buyer: "Director of Procurement",
    created_at: now,
  },
];

export const mockProblemZones: ProblemZoneRow[] = [
  {
    id: "pz1",
    name: "Crypto Custody Compliance Pressure",
    summary:
      "Recurring regulatory pressure on asset managers to meet qualified custodian requirements for digital assets.",
    primary_industry: "Financial Services",
    sub_industry: "Crypto Asset Management",
    primary_buyer: "Chief Compliance Officer",
    secondary_buyer: "General Counsel",
    buyer_confidence: "medium",
    geography_scope: "US",
    timing_label: "trigger_driven",
    pain_theme: "Regulatory custody requirements",
    source_count: 1,
    source_diversity_count: 1,
    pressure_strength_score: 4,
    freshness_score: 5,
    friction_score: 1,
    signal_mix: "trigger-heavy",
    status: "reviewing",
    owner: null,
    notes: "Clustered from Federal Register custody rulemaking signals.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "pz2",
    name: "Healthcare Environmental Vendor Risk",
    summary:
      "Healthcare facilities face third-party environmental compliance exposure through outsourced waste and vendor operations.",
    primary_industry: "Healthcare",
    sub_industry: "Hospital Operations",
    primary_buyer: "Director of Environmental Services",
    secondary_buyer: "VP of Compliance",
    buyer_confidence: "high",
    geography_scope: "US",
    timing_label: "mixed",
    pain_theme: "Third-party vendor compliance gaps",
    source_count: 1,
    source_diversity_count: 1,
    pressure_strength_score: 3,
    freshness_score: 4,
    friction_score: 2,
    signal_mix: "trigger + structural",
    status: "enriching",
    owner: null,
    notes: "Linked to EPA ECHO enforcement context signals.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "pz3",
    name: "Compliance Workflow Template Friction",
    summary:
      "Teams repeatedly request built-in compliance workflow templates and audit trail exports in developer tooling.",
    primary_industry: "Developer Tools",
    sub_industry: "Issue Tracking",
    primary_buyer: "Engineering Manager",
    secondary_buyer: "Compliance Operations Lead",
    buyer_confidence: "medium",
    geography_scope: "Global",
    timing_label: "structural",
    pain_theme: "Manual compliance workarounds",
    source_count: 1,
    source_diversity_count: 1,
    pressure_strength_score: 2,
    freshness_score: 3,
    friction_score: 6,
    signal_mix: "friction-heavy",
    status: "new",
    owner: null,
    notes: "Workflow friction cluster from GitHub Issues signals.",
    created_at: now,
    updated_at: now,
  },
];

export const mockProblemZoneSignals: ProblemZoneSignalRow[] = [
  {
    problem_zone_id: "pz1",
    raw_signal_id: "rs1",
    created_at: now,
  },
  {
    problem_zone_id: "pz2",
    raw_signal_id: "rs2",
    created_at: now,
  },
  {
    problem_zone_id: "pz3",
    raw_signal_id: "rs3",
    created_at: now,
  },
];

export const mockKeywordSets: KeywordSetRow[] = [
  {
    id: "ks1",
    problem_zone_id: "pz1",
    name: "Crypto Custody Compliance Demand",
    topic_layer: "Regulatory custody",
    workflow_layer: "Qualified custodian onboarding",
    product_layer: "Custody compliance tooling",
    buyer_layer: "Chief Compliance Officer",
    seed_keywords: [
      "crypto qualified custodian",
      "digital asset custody compliance",
      "SEC custody rule crypto",
    ],
    expanded_keywords: [
      "qualified custodian requirements crypto",
      "crypto asset manager compliance software",
      "digital asset custody audit trail",
    ],
    rejected_keywords: ["crypto trading bot", "NFT marketplace"],
    geo_target: "US",
    dataforseo_pulled: false,
    last_enriched_at: null,
    notes: "Seed set for demand validation on custody rulemaking pressure.",
    created_at: now,
  },
  {
    id: "ks2",
    problem_zone_id: "pz2",
    name: "Healthcare Vendor Environmental Risk",
    topic_layer: "Third-party environmental compliance",
    workflow_layer: "Vendor risk assessment",
    product_layer: "Healthcare vendor compliance tracker",
    buyer_layer: "Director of Environmental Services",
    seed_keywords: [
      "healthcare vendor environmental compliance",
      "hospital waste vendor audit",
      "EPA healthcare facility compliance",
    ],
    expanded_keywords: [
      "healthcare third party environmental risk",
      "hospital outsourced waste compliance",
    ],
    rejected_keywords: ["medical waste disposal pricing"],
    geo_target: "US",
    dataforseo_pulled: true,
    last_enriched_at: "2026-01-05T10:00:00Z",
    notes: "Partially enriched mock metrics for hospital vendor risk theme.",
    created_at: now,
  },
  {
    id: "ks3",
    problem_zone_id: "pz3",
    name: "Compliance Workflow Template Demand",
    topic_layer: "Developer compliance workflows",
    workflow_layer: "Audit trail export",
    product_layer: "Issue tracker compliance templates",
    buyer_layer: "Engineering Manager",
    seed_keywords: [
      "compliance workflow template",
      "audit trail export software",
      "SOC 2 issue tracker workflow",
    ],
    expanded_keywords: [],
    rejected_keywords: ["free Jira template download"],
    geo_target: "Global",
    dataforseo_pulled: false,
    last_enriched_at: null,
    notes: "Friction-led keyword family; expand after DataForSEO wiring.",
    created_at: now,
  },
];

export const mockKeywordMetrics: KeywordMetricRow[] = [
  {
    id: "km1",
    keyword_set_id: "ks2",
    keyword: "healthcare vendor environmental compliance",
    search_volume: 720,
    trend_direction: "up",
    cpc: 12.4,
    competition: 0.62,
    related_keyword_density: 18,
    geo_signal: "US",
    intent_type: "commercial",
    kept_for_scoring: true,
    created_at: now,
  },
  {
    id: "km2",
    keyword_set_id: "ks2",
    keyword: "hospital waste vendor audit",
    search_volume: 390,
    trend_direction: "stable",
    cpc: 8.9,
    competition: 0.48,
    related_keyword_density: 11,
    geo_signal: "US",
    intent_type: "mixed",
    kept_for_scoring: true,
    created_at: now,
  },
  {
    id: "km3",
    keyword_set_id: "ks1",
    keyword: "crypto qualified custodian",
    search_volume: 1200,
    trend_direction: "up",
    cpc: 18.2,
    competition: 0.71,
    related_keyword_density: 24,
    geo_signal: "US",
    intent_type: "commercial",
    kept_for_scoring: true,
    created_at: now,
  },
];

export const mockMarketProofRecords: MarketProofRecordRow[] = [
  {
    id: "mp1",
    problem_zone_id: "pz1",
    core_search_phrase: "crypto qualified custodian software",
    category_exists: true,
    visible_competitor_count: 8,
    hidden_market_risk: "medium",
    review_sites_found: "G2, Capterra (limited crypto custody category)",
    pricing_visibility: "partial",
    job_posting_evidence: "Compliance analyst roles at digital asset managers",
    spend_evidence: "Limited public spend signals",
    sec_evidence: "SEC custody rulemaking notices and comment letters",
    usaspending_evidence: null,
    segment_wedge: "Mid-size RIAs needing audit-ready custody workflows",
    competition_notes:
      "Incumbents target enterprise; mid-market onboarding remains fragmented.",
    manual_reviewer_notes:
      "Category exists but buyer confusion around qualified custodian vs wallet.",
    market_proof_score: 62,
    created_at: now,
  },
  {
    id: "mp2",
    problem_zone_id: "pz2",
    core_search_phrase: "healthcare vendor environmental compliance software",
    category_exists: true,
    visible_competitor_count: 5,
    hidden_market_risk: "low",
    review_sites_found: "G2, TrustRadius",
    pricing_visibility: "public",
    job_posting_evidence:
      "Environmental services coordinator roles at hospital systems",
    spend_evidence: "EPA enforcement spend references in vendor risk RFPs",
    sec_evidence: null,
    usaspending_evidence: "Healthcare facility compliance contract mentions",
    segment_wedge: "Regional hospital networks with outsourced waste vendors",
    competition_notes:
      "Established EHS platforms exist; wedge is vendor-specific audit workflows.",
    manual_reviewer_notes: "Strong spend and job posting overlap supports wedge.",
    market_proof_score: 71,
    created_at: now,
  },
  {
    id: "mp3",
    problem_zone_id: "pz3",
    core_search_phrase: "compliance workflow template issue tracker",
    category_exists: false,
    visible_competitor_count: 2,
    hidden_market_risk: "high",
    review_sites_found: "None specific to compliance workflow templates",
    pricing_visibility: "hidden",
    job_posting_evidence: "Engineering ops roles mention audit trail exports",
    spend_evidence: null,
    sec_evidence: null,
    usaspending_evidence: null,
    segment_wedge: "Teams exporting audit trails from generic issue trackers",
    competition_notes:
      "Pain is real but category is immature; risk of feature-not-product.",
    manual_reviewer_notes: "Watch for hobby/dev-only friction before scoring.",
    market_proof_score: 38,
    created_at: now,
  },
];

export const mockWorkflowFrictionSignals: WorkflowFrictionSignalRow[] = [
  {
    id: "wf1",
    problem_zone_id: "pz3",
    source: "GitHub Issues",
    source_url: "https://github.com/example/repo/issues/4821",
    title: "Native compliance workflow templates requested",
    summary:
      "Teams repeatedly ask for built-in audit trail exports and compliance workflow templates in issue trackers.",
    friction_type: "missing_workflow_template",
    friction_score: 7,
    repetition_score: 3,
    source_diversity_score: 1,
    workflow_specificity_score: 2,
    manual_workaround_score: 2,
    manual_workaround_detected: true,
    evidence_count: 4,
    accepted_for_scoring: true,
    created_at: now,
  },
  {
    id: "wf2",
    problem_zone_id: "pz1",
    source: "Stack Exchange",
    source_url: "https://stackoverflow.com/questions/example-custody-audit",
    title: "Manual spreadsheet workarounds for custody audit trails",
    summary:
      "Asset managers describe spreadsheet-based custody compliance tracking as error-prone during audits.",
    friction_type: "manual_workaround",
    friction_score: 5,
    repetition_score: 2,
    source_diversity_score: 1,
    workflow_specificity_score: 2,
    manual_workaround_score: 2,
    manual_workaround_detected: true,
    evidence_count: 2,
    accepted_for_scoring: false,
    created_at: now,
  },
  {
    id: "wf3",
    problem_zone_id: "pz2",
    source: "Greenhouse Job Postings",
    source_url: "https://boards.greenhouse.io/example/jobs/12345",
    title: "Hospital vendor compliance coordinator hiring spike",
    summary:
      "Job postings reference manual vendor environmental compliance review workflows and spreadsheet tracking.",
    friction_type: "operational_bottleneck",
    friction_score: 6,
    repetition_score: 2,
    source_diversity_score: 2,
    workflow_specificity_score: 3,
    manual_workaround_score: 1,
    manual_workaround_detected: false,
    evidence_count: 3,
    accepted_for_scoring: true,
    created_at: now,
  },
];
